services:
  db:
    image: postgres:17.7
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123456aA@
      POSTGRES_DB: pgdb
    volumes:
      - ./data:/data
